### ISSUE TITLE
Weird error with GTK

### ISSUE THREAD

**Issue by flamendless** [libsigcplusplus/libsigcplusplus#22] opened 2019-03-10 14:54 UTC
Hi, i get `segfault` error from this simple code:
```cpp
#include <gtkmm/window.h>
#include <gtkmm/box.h>
#include <gtkmm/button.h>

class WindowMain : public Gtk::Window
{
public:

protected:
  Gtk::Box m_box;
  Gtk::Button m_button;
  Gtk::Button m_button2;
  Gtk::Button m_button3;

public:
    WindowMain(Glib::ustring title);
    virtual ~WindowMain();
};
```

and

```cpp
#include "window_main.h"
#include <glibmm/ustring.h>

WindowMain::WindowMain(Glib::ustring title)
{
    set_title(title);
    set_size_request(1024, 720);
    set_border_width(32);

    m_button.set_label("Button1");
    m_button2.set_label("Button2");
    m_button3.set_label("Button3");

    add(m_box);

    m_box.pack_start(m_button);
    m_box.pack_start(m_button2);
    m_box.pack_start(m_button3);

    m_box.show();
    show_all_children();
}

WindowMain::~WindowMain()
{
}
```
However, removing all `m_button3` gives no `segfault`.

i get this error from gdb:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[2019-03-10 22:51:49.311] [info] Start...
[New Thread 0x7ffff349f700 (LWP 22958)]
[New Thread 0x7ffff2c9e700 (LWP 22959)]

Thread 1 "project" received signal SIGSEGV, Segmentation fault.
0x00007ffff6b54ad0 in sigc::trackable::callback_list() const () from /usr/lib/libsigc-2.0.so.0
```

**Comment by kjellahl** [comment] 2019-03-21 12:51
Yes, that's weird. I get no segfault or other error when I test your program.
It will be difficult to help you if I can't reproduce the error.
A backtrace from gdb after the segfault might be useful.

Which libsigc++ version do you use? I tested with 2.10.1.

I added this main program:
```C++
int main(int argc, char* argv[])
{
    auto app = Gtk::Application::create(argc, argv, "org.gtkmm.sigc22");
    WindowMain window("Testing sigc#22");
    app->run(window);
    return 0;
}
```
Have you got a more complicated main program?

**Comment by kjellahl** [comment] 2019-07-04 13:31
@flamendless Do you still get weird errors from libsigc++?

I will close this issue without action unless you can give more information.

**Comment by flamendless** [comment] 2019-07-05 02:10
Oh sorry. I moved from gtk to something else. You can close this now.

**Closed** 2019-07-05 02:10 UTC
Labels: question
